## Please download the new class notes.
### Step 1 : Navigate to the directory where your files are stored.  
Open a terminal. 
<br>Using `cd`, navigate to *inside* the ILAS_Python_for_engineers folder on your computer. 
### Step 3 : Update the course notes by downloading the changes
In the terminal type:

>`git add -A
git commit -m "commit"
git fetch upstream
git merge -X theirs upstream/master`


# Advanced Functions and Building your own Function Library

<br> <a href='#StoringFunctions'>Storing Functions</a>
<br> <a href='#WritingYourOwnLibaray'>Writing Your Own Libaray</a> 
<br> <a href='#Namespaces'>Namespaces</a> 
	<br> &emsp;&emsp; <a href='#LocalNamespace'>The Local Namespace</a> 
<br> <a href='#ModuleSearchPath'>The Module Search Path</a> 
    <br> &emsp;&emsp; <a href='#FilesLocatedSameDirectory'>Files Located in the Same Directory</a> 
    <br> &emsp;&emsp; <a href='#__init__.py'>__init__.py</a> 
    <br> &emsp;&emsp; <a href='#AddingModulesPathSpyder'>Adding Modules to the Path using Spyder</a> 
    <br> &emsp;&emsp; <a href='#AddingModulessitepackages'>Adding Modules to the 'site-packages’</a>
<br> <a href='#VectorisingFunctions'>Vectorising Functions</a>
    <br> &emsp;&emsp; <a href='#VectorisedFunctionsFucntionArguments'>Vectorised Functions as Fucntion Arguments</a> 
<br> <a href='#Broadcasting'>Broadcasting </a>
<br> <a href='#LambdaFunctions'>Lambda Functions</a> 
<br> <a href='#RecursiveFunctions'>Recursive Functions</a> 
     <br> &emsp;&emsp; <a href='#FibonacciSequence'>The Fibonacci Sequence</a> 
<br> <a href='#Generators'>Optional Extension Topic: Generators</a> 
	<br> &emsp;&emsp; <a href='#FibonacciSequenceContinued'>The Fibonacci Sequence (Continued)</a> 
<br> <a href='#Summary'>Summary</a> 
<br> <a href='#TestYourselfExercises'>Test-Yourself Exercises</a>
<br> <a href='#ReviewExercises'>Review Exercises</a>

### Lesson Goal

1. Store functions that you have written in external files and import them to your programs.
2. Write a __recursive function__, a __lambda function__ and (optionally) a generator. 

### Fundamental programming concepts
 - File hierarchy
 - Making your code more readable by storing it in multiple files
 - Using specific function constructs to write code more efficiently

## Storing Functions.
<a id='StoringFunctions'></a>
Python function definitions and constants can be stored in one or more separate files.

This keeps things tidy and allows the functions to be used in multiple programs without re-writing the code.  



The file containig the function dfinitions is called a “module”.

The module name is the file name without the “.py” extension.



These are saved to you computer when you install Numpy.
<br>(Note: Numpy and other widely used packages are automatically installed with Anaconda).

For example, the functions of the Numpy library are stored as a system of:
- __sub-packages__ (sub-folders)
- __modules__ (.py files).

 <img src="img/directory_tree_numpy.png" alt="Drawing" style="width: 400px;"/>

By writing:

    `numpy.linalg.norm([10, 15, 3])`

We are telling the computer to use:
 - the function `norm`...
 - ...from the module `linalg`...
 - ...from the package `numpy`

This function computes the magnitude of a vector described by the input arguments.
<br>x = 20
<br>y = 10
<br>z = 3

<img src="img/3d_position_vector.png" alt="Drawing" style="width: 200px;"/>



In [2]:
import numpy 
numpy.linalg.norm([10, 15, 3])


import numpy as np
np.linalg.norm([10, 15, 3])

18.275666882497067

A directory should contain a file called `__init__.py` for Python to treat the Python files within it as packages.

(However, the examples in this notebook should work without the `__init__.py file`.)

<img src="img/directory_tree__init__.png" alt="Drawing" style="width: 200px;"/>

In the simplest case, `__init__.py` can just be an empty file

It can also execute initialization code for a package.

We will learn about the role of this file later in today's class.

## Writing Your Own Library
<a id='WritingYourOwnLibrary'></a>
It can be useful to store the functions that you write as multiple files.

Typically, you will have one main program into which the other modules are imported.

<img src="img/importing_packages.png" alt="Drawing" style="width: 700px;"/>

This allows you to:
- keep your code readable and tidy
- re-use functions in multiple programs without re-writing the code

Like other libraries, user-defined modules are made available within a program using the Python `import` keyword. 

Example

>`import numpy`

It is general practise to place all import statements at the beginning of the program.

As we hae already studied, imported functions or constants can be called using the module name followed by the function name.

Example

>`numpy.pi`

Let's learnt to import code from a user-defined library...

Open Spyder.

Create two new files with the names:
- `file_A.py`
- `file_B.py`

Save them in a new folder called `functions_example`.

<img src="img/fileA_fileB.png" alt="Drawing" style="width: 700px;"/>

Copy and paste the code from the cell below into `file_B.py`

In [3]:
def print_a_number(number=2):
    print(number)    
    
def type_interrogate(data):
    print(type(data))

Save the file :

File >> Save

In File_A:
- import file_B.py

        import file_B

- call the two functions

        file_B.print_a_number(4)
        
        file_B.type_interrogate('hello')



*What happens if `print_a_number` is called without an argument?*



*What happpens if `type_interrogate` is called without an argument? *

## Namespaces
<a id='Namespaces'></a>
We prefix `print_a_number` and `type_interrogate` with the __namespace__,  `file_B`.

This shows which package we want to import the functions from.





For example, when using the function `numpy.cos()`, we use the name space `numpy` or `np`:

In [4]:
import numpy as np

np.cos(np.pi)

-1.0

The __namespace__ shows we want to use the `cos` function from the Numpy package.

If `cos` appears in more than one package we import, then there will be more than one `cos` function available.

We must make it clear which `cos` we want to use. 




Often, functions with the same name, from different packages, use different algorithms for performing the same or similar operation. 

They may vary in speed and accuracy. 





In some applications we might value accuracy over speed...





#### Example: Square Root

Below are two functions, both named `sqrt`. 

Both functions compute the square root of the input.

 - `math.sqrt`, from the package, `math`, gives an error if the input is a negative number. It does not support complex numbers.
 - `cmath.sqrt`, from the package, `cmath`, supports complex numbers.


In [5]:
import math
import cmath
print(math.sqrt(4))
#print(math.sqrt-5)
#print(cmath.sqrt(-5))

2.0


Two people collaborating on the same program might choose the same name for two functions that perform similar tasks. 

If these functions are in different modules, there will be no name clash since the module name provides a 'namespace'. 

### The Local Namespace.
<a id='LocalNamespace'></a>
Internally, each Python module and program has its own local namespace.

The local namesapce is a “symbol table” which contains the names of all functions and variables that you don't have to prepend with a namespace.

When you import a module with an import statement, only the module’s name gets added to the local namespace – <br>(i.e. the imported module’s local namespace does not get added.)

This is to avoid possible conflicts due to functions with the same name appearing in multiple imported modules. 

This is why you must prefix the function name with the module name. 

You can change the module name in the local namespace.

In file_A.py, you can change the line:

    import file_B

to 

    import file_B as fb
    


We can now call a function using a shortened version of the module name

    file_B.print_a_number(4)
    
to

    fb.print_a_number(4)

If you don't have name collisions, you can import *individual functions* and remove the need for the module name altogether:

        import file_B as fb
        from file_B import print_a_number

        print_a_number(4)
        
        fb.interrogate_type('hello')


To import *all functions* from a module, and remove the need for the module name altogether:

        from file_B import *

        print_a_number(4)

        interrogate_type('hello')

It is inadvisable to use * where you do not know the full content of a module e.g. a library such as Numpy.

It may be appropraite to use * with a small, *specific*, user-defined module. 

##### Try it yourself

Edit the code in file_A.py to:
- import *all* functions from file_B 
- remove the need to use the module name when calling the function

### The Module Search Path
<a id='ModuleSearchPath'></a>
When a module is imported, the Python interpreter searches a collection of directories for a module with that name. 

The collection of directories is called the Python path.

It is stored as a list of strings. 



You can display the Python path for your computer by running:

In [6]:
import sys
print(sys.path)

['', '/anaconda3/lib/python36.zip', '/anaconda3/lib/python3.6', '/anaconda3/lib/python3.6/lib-dynload', '/anaconda3/lib/python3.6/site-packages', '/anaconda3/lib/python3.6/site-packages/aeosa', '/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/Users/hemma/.ipython']


`sys` is a module with useful functions for accessing your computer system.

For a module to be available for import, it must feature in the Python path. 

When you *install* a python module, the action you are doing is adding the module location to the python path.



There are multiple ways to add a module to the search path.

Today we will focus on the simplest, (and arguably the most useful) ways to import modules.  







### Files Located in the Same Directory.
<a id='FilesLocatedSameDirectory'></a>

file_A and file_B are in the same folder.

<img src="img/fileA_fileB.png" alt="Drawing" style="width: 600px;"/>

We therefore refer to them as 'sibling' files.

The file can 'see' it's siblings.

We can import code just by using the `import` keyword.



The file can also 'see' folders in the same directory.

Create a new folder, called `sibling_folder`, in the same directory as file_A.py and file_B.py.

Within this folder, use spyder to create a new file called `file_C.py`. 

<img src="img/sibling_folder.png" alt="Drawing" style="width: 600px;"/>

Copy and paste the code from the cell below into file_C.py

Save the file.

In [7]:
def subtract_and_increment(a, b):
    """"
    Return a minus b, plus 1
    """
    c = a - b + 1
    return c

To import code from file_C to file_A or file_B

>`import sibling_folder.file_C`

>`print(sibling_folder.file_C.subtract_and_increment(8, 10))`

Add the code below the cell below to file_A.py

    from sibling_folder.file_C import *

    print(subtract_and_increment(8, 10))

If a file is located one level or more higher than a program, it cannot automatically be seen by the program. 

To import the file we need to add its location to the Python path. 
<br>(the places the Python interpreter looks for modules).

The easiest way to do this is using the module `sys`.

Use spyder to create a new file in the same folder as `file_C.py`.

Call it `file_D.py`.

<img src="img/fileD.png" alt="Drawing" style="width: 400px;"/>

Copy and paste the following code to `file_D.py`

The code `append`s the directory one level up (`../`) to the python path list.


In [8]:
import sys
sys.path.append('../')
import file_B

ModuleNotFoundError: No module named 'file_B'

The functions from `file_B.py` can now be used within `file_D.py`

e.g.

    file_B.print_a_number()

Notice the addition to the list when we append a directory to the path

In [ ]:
import sys
print(sys.path, end="\n\n")

# Add a directory
sys.path.append('../')
print(sys.path, end="\n\n")

# Remove a directory
sys.path.remove('../')
print(sys.path)

The path allows us to import code located anywhere on the compter.

<img src="img/fileEFG.png" alt="Drawing" style="width: 400px;"/>


- to import code from file_E.py to file_C.py, <br>in file_C.py:
> `sys.path.append('../../another_example')`


<img src="img/fileEFG.png" alt="Drawing" style="width: 400px;"/>



- to import code from file_B.py to file_G.py, <br>in file_G.p:
> `sys.path.append('../functions_example)`

### `__init__.py`
<a id='__init__.py'></a>

The Python interpreter will only check directories that contain a file with the name `__init__.py`.

You should create an empty file with the name `__init__.py` within any directory you wish to import.

The purpose of this is to prevent other python files with the same name (e.g. other projects) from being mistakenly imported. 

As mentioned earlier, the examples in this tutorial will probably work without `__init__.py`.

It is best practise to use `__init__.py`.

Create an empty file with the name `__init__.py` in folders:
- `functions_example`
- `another_example`

### Adding Modules to the Path using Spyder.
<a id='AddingModulesPathSpyder'></a>

Spyder allows users to associate a directory with a *project*. 

The project’s path is added to the Python path. 

*Any* module can be imported directly to another Python file, regardless of file hierarchy within the project. <br>Equivalent functionality can be found in other IDEs.

Projects are completely optional i.e. you can work without creating projects.

In the spyder toolbar click:

Projects >> New project

<img src="img/new_project.png" alt="Drawing" style="width: 300px;"/>

There are two options...

__New directory__
<br>e.g. 
<br>Create a new folder, navigate to *inside* the folder to select it.
<br>All files within this folder will be associated with the same project.

__Existing drectory__ 
<br>e.g. You can select the folder `functions_example`

To add new files to the folder:
1. Right click on the project name in the *Project explorer* window on the left of the screen.
1. Click New >> File...

##### Try it yourself.

Select Projects >> New Project >> Existing directory

Choose the folder `functions_example`.

*Uncomment* the following lines in file_A.py and run the code again.

### Adding Modules to the 'site-packages'.
<a id='AddingModulessite-packages'></a>

`site-packages` is the name of the directory of manually insalled python packages. 

You can find the location of `site-packages` by running:
>`print(sys.path)`

Installed packages such as `numpy` are found here.





If you add a module to thuis directory, it will be universally accessible within the home directory of your computer system.

i.e. You can call it from anywhere by using `import` just as for numpy or any other installed package. 

##### Try it yourself

1. Find the location of `site-packages` in your computer system.

1. Within `site-packages` create a folder called `my_package`.

1. Within `my_package` create:
  - an empty file called `__init__.py`
  - a file called `my_module.py`.

1. In `my_module.py` put a simple print statement e.g.
>`print(2)`

1. Save the file

1. In the terminal type:
>`python3` 

1. To execute the print statement type:
>`import my_package.my_module`

1. To quit the Python interpreter type:
>`quit()`

1. (You can delete the folder `my_package` from site packages. We have finished this example so it is no longer needed.)


<a name="VectorisingFunctions"></a>

## Vectorising Functions

Numpy functions applied to a single array, will be performed on each element in the array. 

The function takes an array of values as an input argument.

In [ ]:
print(np.sqrt(a))
print(a ** (1/2))

For example, we can apply trigonometric functions, elementwise, to arrays, and lists. 

In [ ]:
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
y = [0.0, np.pi/2, np.pi, 3*np.pi/2]
z = (0.0, np.pi/2, np.pi, 3*np.pi/2)

print(np.sin(x))
print(np.cos(y))
print(np.tan(z))

An array of values does not work as an input for all functions.

In [10]:
def func(x):
    if x < 0:
        f = 2 * x
    else:
        f = 3 * x
    return f

x = np.array([2, -2])
# y = func(x) # Run this line after removing the # to see the error generated

This doesn't work because Python doesn't know what to do with the line 

`if x < 0` 

when `x` contains many values. 

For some values of `x` the `if` statement may be `True`, for others it may be `False`. 



A simple way around this problem is to vectorise the function. 

We create a new function that is a *vectorized* form of the original function.

The new function and can be called with an array as an argument.  

In [11]:
funcvec = np.vectorize(func)

print(funcvec(x))

[ 6 -4]


### Vectoried functions as function arguments
<a name="VectorisedFunctionsFucntionArguments"></a>
Functions that receive vectorised arguments are automatically applied to all elements of array inputs. 

This is better exlpained with an example.



Recall the function `is_positive`: 

In [12]:
x = np.array([2, -2])

def is_positive(f, a):
    "Checks if the function value f(x) is positive"
    return f(a) > 0


# Apply is_positive to a non-vectorised function
print(is_positive(func, -3))
print()


# Apply is_positive to a vectorised function
print(x)
is_positive(funcvec, x)

False

[ 2 -2]


array([ True, False])

<a name="Broadcasting"></a>
## Broadcasting

Another source of incompatibility that you are likely to encounter is in trying to use arrays with different shapes for arithmetic operations. 

For example, you have one array that larger and another array that is smaller.
<br>You may want to use the smaller array multiple times to perform an operation (such as a sum, multiplication, etc.) on the larger array.

This is achieved using the broadcasting mechanism. 

The arrays can be broadcast together if all dimensions of the arrays are *compatible*


##### Dimensions are compatible when they are equal.

Consider the example below. `x` and `y` are the same shape, so we can addd them.

In [14]:
x = np.ones((3,4))
print(x)
print(x.shape)

print()

y = np.full((3,4), 4)
print(y)
print(y.shape)

# Add `x` and `y`
x + y

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
(3, 4)


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

##### Dimensions are compatible when the length of at least one of them is equal to 1.

<img src="img/broadcasting1x3.gif" alt="Drawing" style="width: 300px;"/>


In [ ]:
# 1 x 3 array
a = np.arange(1,4)

# integer
b = 2

# 1 x 3 array
result = a * b

print(a)
print()
print(b)
print()
print(result)

In the dimension where `b` has size 1 and `a` has a size greater than 1 (i.e. 3), `b` behaves as if it were copied along that dimension.

In [3]:
# 4 x 1 array
x = np.array([[0],
              [10],
              [20],
              [30]])

# 1 x 3 array
y = np.ones(3)

# 4 x 3 array
a = x * y

print(x)
print()
print(y)
print()
print(a)


NameError: name 'np' is not defined

<img src="img/broadcasting4x3.gif" alt="Drawing" style="width: 300px;"/>

In [2]:
# a: 4 x 3 array (see cell above)

# 1 x 3 array
b = np.arange(3)

# 4 x 3 array
result = a + b

print(a)
print()
print(b)
print()
print(result)

SyntaxError: invalid syntax (<ipython-input-2-9dce3db43401>, line 1)

The size of the output array is the *maximum* size along each dimension of the input arrays.

The 4x3 and 1x4 arrays shown in the cell below cannot be broadcast together.
<br>The dimensions 3 and 4 are incompatible.

<img src="img/broadcasting_mismatch.gif" alt="Drawing" style="width: 300px;"/>

Recall, the function `np.insert` that we used earlier.

An integer (length=1) can be broadcast into an array of any size. 

In [16]:
# Add items to an array
b = np.array([[1, 1], 
              [2, 2], 
              [3, 3]])

# insert value 4, at position 1, on axis 1, in array b
b = np.insert(b, 1, 4, axis=1)
print(b)

[[1 4 1]
 [2 4 2]
 [3 4 3]]


Here are some examples of practical applications of broadcasting.

### Broadcasting Example: Calorie Calculator

Let's say we have a large data set; each datum is a list of parameters.

Example datum: a type of food and the the amount of fat, protein and carbohydrate in a serving of that food.

Our data set of food nutrients might look something like the table below:

|Food (100g) |Fat(g)|Protein (g)|Carbohydrate (g)|
|------------|----- |-----------|----------------|
|Almonds     |    49|         21|              22|                         
|Peas        |     0|          5|              14|   
|Avocado     |    15|          2|               9|
|Kale        |     1|          3|              10|  

   


By applying the following sclaing factors, we can calculate the number of calories in a food type due to fat, protein and carbohydrate:
 -  fat: 9 cal/g
 -  protein: 4 cal/g
 -  carbohydrate 4 cal/g
 
Using what we have studied so far, we could convert the table to calories using a loop:


```python

nutrients = np.array([[49, 21, 22],
                      [0,   5, 14],
                      [15,  2,  9],
                      [ 1,  3, 10]])

cal_convert = np.array([9, 4, 4])

calories = np.empty((4,3))

for index, value in enumerate(nutrients):
    calories[index] = value * cal_convert
    
```
    

However, it is faster and more concise to broadcast the two arrays together: 

In [4]:

nutrients = np.array([[49, 21, 22],
                      [0,   5, 14],
                      [15,  2,  9],
                      [ 1,  3, 10]])

cal_convert = np.array([9, 4, 4])

calories = nutrients * cal_convert

print(calories)

NameError: name 'np' is not defined

### Broadcasting Example: Vector Quantisation Algorithm
This is a simple algorithm used for catagorisation.
<br>It determines which catagory a data point should belong to from its closest proximity to a set of values representing possible catagories.
<br>Each value represents the mean of the corresponding catagory.





<br>For example, colour quantisation is used in image processing reduces the number of distinct colors used in an image, while maintianing visual similarity to the original image. 

<table><tr><td> 
<img src="img/un_quantised_cat.png" alt="Drawing" style="width: 300px;"/> </td><td> 
<img src="img/quantised_cat.png" alt="Drawing" style="width: 300px;"/> </td><td> 
</table>

CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=1477223

<br>In the plot below, each of the circles represents the mean height and weight of athletes grouped by type. 
<br>The square represents the height and weight of an athlete to be classified. 
<img src="img/vector_quantisation.png" alt="Drawing" style="width: 500px;"/>


To find the closet point:
1. Use broadcasting to find the difference between the position of the __square__ and the position of each __circle__ in the x and y directions. <br>
1. Find the distance, $d$ from the square, $s$ to each circle, $c$ using: <br>$d = \sqrt{(x_{c}-x_{s})^2 + (y_{c}-y_{s})^2}$ <br>
1. Choose the group corresponding to the minimum distance, $d_{min}$

In [18]:
athlete = np.array([111.0,188.0])

categories = np.array([[102.0, 203.0],
                       [132.0, 193.0],
                       [45.0, 155.0],
                       [57.0, 173.0]])

# 1. broadcast
diff = categories - athlete

# 2. distance to each point (magnitude of values along axis 1 for each datum)
# dist = np.linalg.norm(diff,axis=1)
dist = np.sqrt(np.sum(diff**2,axis=1))

# 3. which group?
nearest = np.argmin(dist)
print(nearest)

0


The nearest group is index 0 of the array `catagories`.
<br>Based on mean height and weight, the athlete is most likely to be a basketball player.

## Lambda Functions
<a id='LambdaFunctions'></a>

When we create a function using the `def` keyword we assign it to a function name. 
<br> e.g. in the function above we assign the name fibonacci:
```python
def sum_and_increment():
```



We can also create an un-named function using the `lambda` keyword.

A lambda function: 
 - may contain a single expression, only
 - must always return a value
 


The next example shows the definition of a function and a lambda function.
<br> Both perform exactly the same task; computing the value of `x`$^2$.

Both can be called using:
```python
square(5)
```
with the number in brackets being the value that you want to square. 

In [5]:
# function definition expressed on two lines
#def square(x):
#    return x ** 2

# function definition expressed on one line
def square(x) :  return x ** 2

print(square(5))

# un-named function
square = lambda x : x ** 2
    
print(square(5))

25
25


Lambda functions can have multiple inputs and outputs.

Outputs are returned as a data structure.

In [6]:
lam_func = lambda x, y: [x+y, x-y]

print(lam_func(2, 1))

[3, 1]


So what is the point of the un-defined function? 


- Short functions can be written more concisely.
- Functions can be embedded within main body of the code, for example within a list.
- This is not possible with a regular function...


In [8]:
# Regular function definition

# 1. Define functions
def function1(x): return x ** 2
def function2(x): return x ** 3
def function3(x): return x ** 4

# 2. Compile list
funcs = [function1, function2, function3]

# 3. Call each function
for function in funcs:
    print(function(5))
    
    
    

25
125
625


In [ ]:
# Lambda function

# 1. Define lamda functions within list
callbacks = [lambda x : x ** 2, lambda x : x ** 3, lambda x : x ** 4]

# 3. Call each function
for function in callbacks:
    print(function(5))

## Recursive Functions
<a id='RecursiveFunctions'></a>
A recursive function is a function that makes calls to itself.

Let's consider a well-known example, the Fibonacci series of numbers.

### The Fibonacci Sequence
<a id='FibonacciSequence'></a>
An integer sequence characterised by the fact that every number (after the first two) is the sum of the two preceding numbers. 

i.e. the $n$th term $f(n)$ is computed from the preceding terms $f(n-1)$ and $f(n-2)$. 

$$
f(n) = f(n-1) + f(n-2)
$$

for $n > 1$

$f(0) = 0$ and $f(1) = 1$. 

Due to this dependency on previous terms, we say the series is defined __recursively__.









The number sequence appears in many natural geometric arrangements: 

<img src="img/FibonacciSpiral.png" alt="Drawing" style="width: 200px;"/> 
<img src="img/fibonacci-whelk.jpg" alt="Drawing" style="width: 200px;"/>

Below is a function that computes the $n$th number in the Fibonacci sequence using a `for` loop inside the function.

In [9]:
def fib(n):
    "Compute the nth Fibonacci number"
    # Starting values for f0 and f1
    f0, f1 = 0, 1

    # Handle cases n==0 and n==1
    if n == 0:
        return 0
    elif n == 1:
        return 1
    
    # Start loop (from n = 2)    
    for i in range(2, n + 1):
        
        # Compute next term in sequence
        f = f1 + f0

        # Update f0 and f1    
        f0 = f1
        f1 = f
        
    # Return Fibonacci number
    return f

print(fib(10))




55


The __recursive function__ below return the same result.

It is simpler and has a more "mathematical" structure.

In [ ]:
def f(n): 
    "Compute the nth Fibonacci number using recursion"
    if n == 0:
        return 0  # This doesn't call f, so it breaks out of the recursion loop
    elif n == 1:
        return 1  # This doesn't call f, so it breaks out of the recursion loop
    else:
        return f(n - 1) + f(n - 2)  # This calls f for n-1 and n-2 (recursion), and returns the sum 

print(f(2))



Care needs to be taken when using recursion that a program does not enter an infinite recursion loop. 

There must be a mechanism to 'break out' of the recursion cycle. 

<a id='Generators'></a>
## Optional Extension Topic: Generators 

When a Python function is called:
1. It excutes the code within the function
1. It returns any values 
<br>The state of the variables within the function are not retained.

i.e. the next time the function is called it will process the code within the function exactly as before.



A generator is a special type of function.
 - They contain the keyword `yield`.
 - When called, any variables within the function retain their value at the end of the function call. 
 - Values following the keyword `yield` are "returned" by the generator function.



Intuitively, generators can be used to increment a value. 

Let's consider an example.

This function increments a value every time it is called. 

In [ ]:
x = 1

def process_value():
    
    # keyword global required to re-assign value of variable
    global x

    if x > 4:
        i = (str(x) + " > 4")
    elif x > 2:
        i = (str(x) + " > 2")
    elif x > 0:
        i = (str(x) + " > 0")
    else:
        i = str(x)
    
    #"Increment global x by +1 "
    x += 1 
    
    return i    
    
process_value()

In [ ]:
x = 1

for i in range(5):
    print(process_value())


A more concise way to express this is as a generator.

A generator takes the following form:
1. Use the function definition line as normal
1. Initialise the variable(s) you are going to increment.
1. Start a while loop. `while True` creates an infinite while loop. <br> The program won't get stuck as it will only execute .
1. The value to yield each loop.
1. The increment operation to perform each loop must come *after* `yield`.

In [ ]:
# `def` is used as normal
def incr():
    
    # create an initial value, i
    i = 1
    
    # while loop
    while True:
        
        # the value to return at each call
        yield i 
        
        # the operation to perform on i at each call
        i += 1  


We create a *generator object* by assigning the generator to a name:

In [ ]:
inc = incr()

The next value can be called using the `next` keyword:

In [ ]:
print(next(inc))
print(next(inc))
print(next(inc))

To change the function process_value to a generator function:
1. Use the function definition line as normal
1. Initialise x inside the function (remove reference to global variable)
1. Start a while loop. 
1. The value to `yield` each loop.
1. The operation to perform each loop ( `x += 1` ) must come *after* `yield`.  

In [ ]:
# x = 1

def process_value():
    
    # initial value of x defined inside function
    x = 1
    
    # while loop
    while True:
    
        # Return a value that depends on the input value y
        if x > 4:
            i = (str(x) + " > 4")
        elif x > 2:
            i = (str(x) + " > 2")
        elif x > 0:
            i = (str(x) + " > 0")
        else:
            i = str(x)

        # the value to return at each call
        yield i 

        # Increment global x by +1 
        # global x
        x += 1 
    
    #return i 
    
process = process_value()

In [ ]:
for i in range(6):
    print(next(process))


By creating an input variable, you can change the initial value of the variable to be incremented.

In [ ]:
# x = 1

def process_value(y):
    
    # initial value of x defined inside function
    x = y
    
    # while loop
    while True:
    
        # Return a value that depends on the input value y
        if x > 4:
            i = (str(x) + " > 4")
        elif x > 2:
            i = (str(x) + " > 2")
        elif x > 0:
            i = (str(x) + " > 0")
        else:
            i = str(x)

        # the value to return at each call
        yield i 

        # Increment global x by +1 
        # global x
        x += 1 
    
    #return i 
    
process = process_value(3)

In [ ]:
for i in range(6):
    print(next(process))

### The Fibonacci Sequence (Continued)
<a id='FibonacciSequenceContinued'></a>
The following example shows how a generator can be used to produce the Fibonacci number sequence. 

In [ ]:
def fibonacci():
    # first two values in the sequence
    a = 0
    b = 1
    
    # infinite while loop
    while True:
        
        # value to return
        yield a        
        
        # a and b are redefined at the same time
        a, b = b, a + b
        
# Create a generator object called fib        
fib = fibonacci()

# Call single loops of the function
for i in range(6):
    print(next(fib))

# Summary
<a id='Summary'></a>
- Python (.py) files can be written, saved (and run) in a text editor or IDE (Integrated Development Environment).
 - Python files can can run from the command line.
 - Storing functions and variables in seperate files and importing them for use can keep your program organised and tidy.
 - The python built-in `input` keyword can be used to generate user-input to the program while it is running.
- An un-named function can be created using the `lamda` keyword.
- A generator function is created when the keyword `yield` is included in the function block.
- Varibales in a generator function their state from when the function was last called.
- The python built in `next()` function can be used to continue execution of a generator function by one iteration.
 

<a id='TestYourselfExercises'></a>
# Test-Yourself Exercises

Compete the Test-Youself exercises below.

Save your answers as .py files and email them to:
<br>philamore.hemma.5s@kyoto-u.ac.jp

# Test-Yourself Exercise : User-defined Library
1. Create a new folder with the name `library_homework`
1. Inside the `library_homework` folder create:
    - a file with the name `my_library.py`
    - a folder with the name `my_project`
1. Inside the `my_project` folder create a file with the name `my_program.py`.

1. In the file `my_library.py`, define a function with the name `my_func`:

    - Inputs: `x`, `y`

    - Outputs: A list:
        - Element 0 = $cos(x) + 10y$  
        - Element 1 = $sin(x) - 20y$

1. Call the function `my_func` from the program `my_program.py`

In [ ]:
# User-defined library

# Test-Yourself Exercise : Lambda functions

Create a list of three elements, where each element is a lambda function that returns a function of variable `x`:
- Element 0 = $cos(x)$  
- Element 1 = $sin(x)$
- Element 2 = $tan(x)$

Use *nested loops* to call each function for all positive integers lower than 4. 



In [ ]:
# Lambda functions

# Review Exercises



### Review Exercise:  Recursive Functions

The factorial of a positive integer $n$ is:

\begin{align}
n! = \prod_{i=1}^{n} i =1 \cdot 2 \cdot 3 \cdot ... (n - 2) \cdot (n - 1) \cdot n
\end{align}

We can write this *recursively*.
<br>This means we use the value of $(n-1)!$ to compute the value of $n!$:

$$
n! = (n-1)! n 
$$

Note: $0! = 1$
 
e.g. 
<br> $1! = 1 \cdot 0! = 1 $
<br> $2! = 2 \cdot 1! = 2 \cdot 1 = 2$
<br> $3! = 3 \cdot 2! = 3 \cdot 2 \cdot 1 = 6$
<br> $4! = 4 \cdot 3! = 4 \cdot 3 \cdot 2 \cdot 1 = 24$

A recursive function is a function that calls itself. 
<br><a href='#RecursiveFunctions'>Jump to Recursive Functions</a>

__(A)__ In the cell below, write a __recursive function__ called `factorial` to compute $n!$ of an input argument `n`:

__Input:__ Numerical variable `n`

__Output:__ `factorial(n) = factorial(n-1)*n` 


Include a doc-string to say what your function does. 

Test your function for correctness using hand calculations. 

<br>
__(B)__ The formula above only applies to __positive integers__(with a specific exception for 0). 
<br>Include a check to make sure the input value is a positive integer or zero. 

Show the output of your function for several input values.



In [ ]:
# A function to compute n! for input n

In [ ]:
#Example solution
